"""
RiskLens AI - PDF Report Generator
Produces a bank-style single-applicant credit risk report, and a
portfolio-level risk summary report for bulk uploads.
"""
import os
from datetime import datetime
from fpdf import FPDF
from src.config import REPORT_DIR

BRAND = (17, 45, 78)       # deep navy
ACCENT = (0, 153, 153)     # teal
RISK_COLORS = {
    "LOW": (39, 174, 96),
    "MEDIUM": (241, 196, 15),
    "HIGH": (230, 126, 34),
    "CRITICAL": (192, 57, 43),
}


def _s(text) -> str:
    """Sanitizes any string for the core Helvetica (latin-1) font used in
    this report, replacing common unicode punctuation with ASCII equivalents
    so report generation never crashes on borrower names or SHAP text."""
    text = str(text)
    replacements = {
        "\u2014": "-", "\u2013": "-", "\u2018": "'", "\u2019": "'",
        "\u201c": '"', "\u201d": '"', "\u20b9": "Rs. ", "\u2026": "...",
    }
    for uni, ascii_ in replacements.items():
        text = text.replace(uni, ascii_)
    return text.encode("latin-1", "ignore").decode("latin-1")


class RiskLensPDF(FPDF):
    def header(self):
        self.set_fill_color(*BRAND)
        self.rect(0, 0, 210, 22, "F")
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 16)
        self.set_xy(10, 6)
        self.cell(0, 10, "RiskLens AI", ln=0)
        self.set_font("Helvetica", "", 10)
        self.set_xy(-80, 8)
        self.cell(70, 10, "AI-Powered Credit Risk Report", align="R")
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, f"Generated by RiskLens AI  |  {datetime.now().strftime('%d %b %Y %H:%M')}  |  Page {self.page_no()}", align="C")


def _section_title(pdf, text_):
    text_ = _s(text_)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(*BRAND)
    pdf.cell(0, 8, text_, ln=1)
    pdf.set_draw_color(*ACCENT)
    pdf.set_line_width(0.5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)


def generate_single_report(applicant: dict, result: dict) -> str:
    pdf = RiskLensPDF()
    pdf.add_page()
    pdf.set_text_color(0, 0, 0)

    _section_title(pdf, "Applicant Profile")
    pdf.set_font("Helvetica", "", 10)
    fields = [
        ("Name", applicant.get("full_name")), ("Age", applicant.get("age")),
        ("Occupation", applicant.get("occupation")), ("Employment Type", applicant.get("employment_type")),
        ("Years of Employment", applicant.get("years_of_employment")),
        ("Annual Income", f"Rs. {applicant.get('annual_income'):,.0f}"),
        ("Loan Amount", f"Rs. {applicant.get('loan_amount'):,.0f}"),
        ("Loan Purpose", applicant.get("loan_purpose")),
        ("Existing Debt", f"Rs. {applicant.get('existing_debt'):,.0f}"),
        ("Monthly EMI", f"Rs. {applicant.get('monthly_emi'):,.0f}"),
        ("Credit Score", applicant.get("credit_score")),
        ("Open Accounts", applicant.get("open_accounts")),
        ("Previous Defaults", applicant.get("previous_defaults")),
    ]
    for label, val in fields:
        pdf.cell(60, 7, _s(f"{label}:"), border=0)
        pdf.cell(0, 7, _s(val), border=0, ln=1)
    pdf.ln(4)

    _section_title(pdf, "Risk Assessment Result")
    cat = result["risk_category"]
    color = RISK_COLORS.get(cat, (100, 100, 100))

    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(60, 8, "Risk Score:", ln=0)
    pdf.cell(0, 8, f"{result['risk_score']}/100", ln=1)

    pdf.cell(60, 8, "Default Probability:", ln=0)
    pdf.cell(0, 8, f"{result['default_probability']*100:.1f}%", ln=1)

    pdf.cell(60, 8, "Risk Category:", ln=0)
    pdf.set_text_color(*color)
    pdf.cell(0, 8, _s(cat + " RISK"), ln=1)
    pdf.set_text_color(0, 0, 0)

    pdf.cell(60, 8, "Recommendation:", ln=0)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(*color)
    pdf.cell(0, 8, _s("LOAN " + result["recommendation"]), ln=1)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 10)
    pdf.ln(4)

    _section_title(pdf, "Key Risk Drivers (Explainable AI)")
    pdf.set_font("Helvetica", "", 10)
    for reason in result["top_risk_drivers"]:
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(0, 7, _s(f"- {reason}"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    _section_title(pdf, "Financial Ratios")
    fm = result.get("financial_metrics", {})
    ratio_fields = [
        ("Debt-to-Income Ratio", fm.get("dti")),
        ("EMI-to-Income Ratio", fm.get("eti")),
        ("Loan-to-Income Ratio", fm.get("lti")),
        ("Credit Utilization Score", fm.get("cu_score")),
        ("Rule-Based Financial Risk Score", fm.get("financial_risk_score")),
    ]
    for label, val in ratio_fields:
        pdf.cell(80, 7, _s(f"{label}:"), border=0)
        pdf.cell(0, 7, _s(val), border=0, ln=1)

    os.makedirs(REPORT_DIR, exist_ok=True)
    safe_name = "".join(c for c in str(applicant.get("full_name", "applicant")) if c.isalnum() or c in " _-").strip()
    filename = f"risk_report_{safe_name}_{datetime.now().strftime('%Y%m%d%H%M%S')}.pdf"
    path = os.path.join(REPORT_DIR, filename)
    pdf.output(path)
    return path


def generate_portfolio_report(summary: dict, top_risky: list) -> str:
    """summary: dict with totals; top_risky: list of dicts (name, risk_score, risk_category)"""
    pdf = RiskLensPDF()
    pdf.add_page()

    _section_title(pdf, "Portfolio Risk Summary")
    pdf.set_font("Helvetica", "", 10)
    for label, val in summary.items():
        pdf.cell(70, 7, _s(f"{label}:"), border=0)
        pdf.cell(0, 7, _s(val), border=0, ln=1)
    pdf.ln(4)

    _section_title(pdf, "Top High / Critical Risk Borrowers")
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(*BRAND)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(70, 7, "Name", 1, 0, "L", True)
    pdf.cell(40, 7, "Risk Score", 1, 0, "C", True)
    pdf.cell(40, 7, "Category", 1, 0, "C", True)
    pdf.cell(40, 7, "Recommendation", 1, 1, "C", True)

    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 9)
    for row in top_risky[:25]:
        color = RISK_COLORS.get(row.get("risk_category", ""), (0, 0, 0))
        pdf.cell(70, 7, _s(str(row.get("full_name", ""))[:35]), 1)
        pdf.cell(40, 7, _s(row.get("risk_score", "")), 1, 0, "C")
        pdf.set_text_color(*color)
        pdf.cell(40, 7, _s(row.get("risk_category", "")), 1, 0, "C")
        pdf.set_text_color(0, 0, 0)
        pdf.cell(40, 7, _s(row.get("recommendation", "")), 1, 1, "C")

    os.makedirs(REPORT_DIR, exist_ok=True)
    filename = f"portfolio_risk_report_{datetime.now().strftime('%Y%m%d%H%M%S')}.pdf"
    path = os.path.join(REPORT_DIR, filename)
    pdf.output(path)
    return path
